platform :ios, '8.0'


# 当使用use_frameworks!的时候，出现Class XXXX is implemented in both  xx. One of the two will be used. Which one is undefined.
# 当不使用use_frameworks!的时候，直接编译报错：duplication class XXXX
# https://www.jianshu.com/p/38fc402dac6c
use_frameworks!



target 'RXBugCrashDemo' do

pod 'KSCrash'
#pod 'Bugtags'


inhibit_all_warnings!

end

